Project/Areas/User/Controllers/UserHomeController.cs
using Project.BuisnessLogic.Manage;
using Project.Core.Stuff;
using Project.SQLDataAccess.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.Areas.User.Controllers
{
    [Authorize]
    public class UserHomeController : Controller
    {
        private readonly IManager<Objective, Guid> _repo;

        public UserHomeController() { }

        public UserHomeController(IManager<Objective,Guid> repo)
        {
            
            List<SelectListItem> dropdownItems = new List<SelectListItem>();
            dropdownItems.AddRange(new[]{
                            new SelectListItem() { Text = "To do", Value = "1" },
                            new SelectListItem() { Text = "Done", Value = "2" },
                            new SelectListItem() { Text = "Review", Value = "3" },
                            new SelectListItem() { Text  = "In progress", Value = "4" },
                            new SelectListItem() { Text  = "Rework", Value = "5" } });
            ViewBag.Statuses = dropdownItems;
            _repo = repo;
        }
        // GET: User/UserHome
        public ActionResult Index()
        {
            var res = _repo.GetAll().Where(x => x.UserID == (Guid)System.Web.HttpContext.Current.Session["UserID"]);
            return View(res);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Objective model)
        {
            model.UserID = (Guid)System.Web.HttpContext.Current.Session["UserID"];
            _repo.Create(model);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(Objective model)
        {
            return View(_repo.Get(model.Id));
        }
        [HttpPost]
        public ActionResult Edit(Objective model, Guid id)
        {
            _repo.Edit(model, id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Delete(Guid id,object o)
        {
            return View(_repo.Get(id));
        }
        [HttpPost]
        public ActionResult Delete(Guid id)
        {
            _repo.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Project/Areas/User/Views/Shared/_Layout.cshtml
@using Project.Helpers
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Мои таски", "Index", "UserHome", new { area = "User" }, new { @class = "nav navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav pull-right">
                    <li>@Html.LoginLink("Sign in", "Dear friend {0}, sign out", "SignIn", "SignOut", "UserLogin")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My application for A-Level :)</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>